version: '3'

services:
  mysql:
    image: mysql:8.0.36
    container_name: mysql-gg-games-docker
    ports:
      - "3308:3306"
    environment:
      - MYSQL_DATABASE=gg-games-docker
      - MYSQL_USER=gg-games-docker
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
